--Tabla domicilios
DROP TABLE IF EXISTS domicilios;
CREATE TABLE domicilios (ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(200) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR (100) NOT NULL,
PROVINCIA VARCHAR (100) NOT NULL);


--Tabla odontologos
DROP TABLE IF EXISTS odontologos;
CREATE TABLE odontologos (ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR (100) NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
MATRICULA INT NOT NULL);

--Tabla pacientes
DROP TABLE IF EXISTS pacientes;
CREATE TABLE pacientes (ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR (100) NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
EMAIL VARCHAR (100) NOT NULL,
DNI INT NOT NULL,
FECHA_INGRESO DATE NOT NULL,
DOMICILIO_ID INT NOT NULL,
ODONTOLOGO_ID INT);


--Domicilios
INSERT INTO domicilios (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Digital Street', 100, 'Moron', 'Buenos Aires');
INSERT INTO domicilios (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('House Street', 200, 'Grand Bourg', 'Buenos Aires');

--Odontologos
INSERT INTO odontologos (APELLIDO, NOMBRE, MATRICULA) VALUES ('Carlos', 'Roberto', 666);
INSERT INTO odontologos (APELLIDO, NOMBRE, MATRICULA) VALUES ('Messi', 'Lio', 111);

--Pacientes
INSERT INTO pacientes (APELLIDO, NOMBRE, EMAIL, DNI, FECHA_INGRESO, DOMICILIO_ID, ODONTOLOGO_ID) VALUES ('Rampazzo', 'Franco', 'franco@gmail.com', 123, '2020-01-01', 1, 1);
INSERT INTO pacientes (APELLIDO, NOMBRE, EMAIL, DNI, FECHA_INGRESO, DOMICILIO_ID, ODONTOLOGO_ID) VALUES ('Test', 'Horacio', 'horacio@gmail.com', 321, '2022-01-01', 2, 2);



